title: "חזי באר | פסיכולוג קליני - טיפול CBT ב-OCD וחרדה"
description: "פסיכולוג קליני מומחה בטיפול קוגניטיבי-התנהגותי"
url: "https://hezibeer.co.il"
author: "חזי באר"
social_image: <img src="{{ profile_image | relative_url }}" alt="תמונת פרופיל"> # תמונה שתוצג בוואטסאפ
# פרטי קשר
whatsapp_number: "972523865888"
license_number: "27145665"
lang: "he"
direction: "rtl"

collections:
  articles:
    output: true
    permalink: /articles/:path/
  services:
    output: true
    permalink: /services/:path/
  media:
    output: true
    permalink: /media/:path/

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap